### ISSUE TITLE
publish stats for a handler

### ISSUE THREAD

**Issue by squirrely** [baris/fullerite#17]
This could be that each handler just writes its data to its own endpoint, or we make some shared system? I am open to options. 

Mainly we want to make it so that we can get the timings for signalfx's post. If easily we'd want to publish:
  - ssl connection time
  - time to first byte
  - total request time
  - metrics in flush

**Comment by baris** [comment]
We currently publish the total request time and sent it to the same handler.

**Comment by squirrely** [comment]
We should also report the number of metrics sent and the number of metrics dropped

**Comment by baris** [comment]
After with cbc3107 we publish send & dropped from all handlers.
