### ISSUE TITLE
if the config is not valid fullerite should fail out better

### ISSUE THREAD

**Issue by squirrely** [baris/fullerite#18]
If the config isn't valid json we should say so and fail out soon. Currently it 'kinda' fails.

**Comment by jaxxstorm** [comment]
I've got a commit that fixes this here: https://github.com/jaxxstorm/fullerite/commit/b2b15c4c399edd15d401309fb2ca7c6e513c5812

But I'm struggling with the tests as I'm pretty new to go.

**Comment by baris** [comment]
#21 fixed this.
