### ISSUE TITLE
HandlerEmitTiming genereating NaN metrics

### ISSUE THREAD

**Issue by ericchu94** [baris/fullerite#32]
I keep getting this error. And it is due to a HandlerEmitTiming metric having value NaN.

Looking at [here](https://github.com/baris/fullerite/blob/f423089f2bb7c8b43386973f5d07552e87b17dc0/src/fullerite/handler/kairos.go#L78)

Assuming `bufferSizeLimitReached = false`
If a metric comes in at such a time where `emitHandlerIntervalPassed = true`, but `doEmit = false`, then `k.resetEmissionTimes()` runs.
If the next time a metric comes in is after another `k.interval` of time, and both `emitHandlerIntervalPassed = true` and `doEmit = true`, then `k.makeEmissionTimeMetric()` runs.

Since no runs of `k.emissionTimes = append(k.emissionTimes, emissionTimeInSeconds)` occurred between the `k.resetEmissionTimes()` and the `k.makeEmissionTimeMetric()`, then `m.Value = value / float64(len(handler.emissionTimes))` [here](https://github.com/baris/fullerite/blob/f423089f2bb7c8b43386973f5d07552e87b17dc0/src/fullerite/handler/handler.go#L157) gets a value of NaN

Edit: This is a lot more likely to happen when handler interval == collector interval

**Comment by baris** [comment]
It sounds like this would also happen on the first emit. handler.Run should handle this case. @ericchu94, would you like to take this ticket?

**Comment by baris** [comment]
This should be fixed with #35
