### ISSUE TITLE
KairosDB rejects process names with equals (=) or colons (:)

### ISSUE THREAD

**Issue by ericchu94** [baris/fullerite#33]
Kairos does not allow equals or colons in tag values.

ProcStatus may report colons or equals (eg: kworker/0:0)

Either sanitize the process names (remove/replace colons and equals?) or drop support for processes with colons and equals.

**Comment by ericchu94** [comment]
Making this sanitation common across all handlers to ensure metric name consistency.

**Comment by baris** [comment]
fixed with #37. Thanks @ericchu94!
